// Sample data for Bazzar marketplace — Qatar market

window.BAZZAR_CATEGORIES = [
  { id: "vehicles",   label: "Vehicles",         icon: "car",      count: "24,180", sub: ["Cars", "Motorcycles", "Boats", "Heavy Vehicles", "Parts & Accessories"] },
  { id: "property",   label: "Real Estate",      icon: "home",     count: "18,422", sub: ["Apartments for Rent", "Villas for Sale", "Commercial", "Rooms", "Short Term"] },
  { id: "electronics",label: "Electronics",      icon: "device",   count: "31,094", sub: ["Mobile Phones", "Laptops", "TVs", "Cameras", "Gaming", "Audio"] },
  { id: "furniture",  label: "Home & Furniture", icon: "sofa",     count: "12,560", sub: ["Sofas", "Beds", "Dining", "Lamps", "Decor", "Storage"] },
  { id: "fashion",    label: "Fashion & Beauty", icon: "shirt",    count: "8,914",  sub: ["Womenswear", "Menswear", "Watches", "Bags", "Perfumes", "Jewelry"] },
  { id: "jobs",       label: "Jobs",             icon: "briefcase",count: "4,201",  sub: ["Full-time", "Part-time", "Freelance", "Domestic Help", "Education"] },
  { id: "services",   label: "Services",         icon: "wrench",   count: "6,338",  sub: ["Cleaning", "Moving", "Repairs", "Tutoring", "Beauty", "Events"] },
  { id: "pets",       label: "Pets & Animals",   icon: "paw",      count: "1,847",  sub: ["Cats", "Dogs", "Birds", "Fish", "Accessories"] },
  { id: "sports",     label: "Sports & Hobbies", icon: "ball",     count: "5,612",  sub: ["Fitness", "Bicycles", "Camping", "Music", "Books"] },
  { id: "kids",       label: "Kids & Babies",    icon: "baby",     count: "3,290",  sub: ["Toys", "Strollers", "Clothing", "Furniture"] },
  { id: "garden",     label: "Garden & Outdoor", icon: "leaf",     count: "1,118",  sub: ["Plants", "Tools", "Furniture", "BBQ"] },
  { id: "business",   label: "Business & Equip", icon: "package",  count: "2,776",  sub: ["Restaurant Supplies", "Office", "Construction"] },
];

window.BAZZAR_CITIES = ["Doha", "West Bay", "Lusail", "Al Wakrah", "Al Khor", "Mesaieed", "Education City", "The Pearl", "Al Rayyan", "Al Daayen"];

window.BAZZAR_LISTINGS = [
  { id: "L-2401", title: "2022 Toyota Land Cruiser GXR — Single Owner, GCC", price: 245000, currency: "QAR", category: "vehicles", subcategory: "Cars", location: "West Bay, Doha", postedAgo: "2h", seller: "Khalid M.", sellerSince: "2021", featured: true, condition: "Used", swatch: "warm", tags: ["GCC Specs", "Service History", "Warranty"], thumbs: 4, photo: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&q=75&auto=format&fit=crop", desc: "Immaculate condition, full service history at agency. Negotiable for serious buyers only. No accidents, original paint throughout." },
  { id: "L-2402", title: "iPhone 15 Pro Max 256GB — Natural Titanium, Sealed", price: 4200, currency: "QAR", category: "electronics", subcategory: "Mobile Phones", location: "The Pearl", postedAgo: "32m", seller: "Layla A.", sellerSince: "2023", featured: true, condition: "New", swatch: "cool", tags: ["Sealed Box", "1yr Warranty"], thumbs: 3, photo: "https://images.unsplash.com/photo-1696446702183-be2e35b3a5e6?w=800&q=75&auto=format&fit=crop", desc: "Brand new, factory sealed. Authentic with regional warranty. Pickup West Bay or Pearl." },
  { id: "L-2403", title: "Spacious 2BR Apartment with Marina View — Lusail", price: 9500, currency: "QAR/mo", category: "property", subcategory: "Apartments for Rent", location: "Marina District, Lusail", postedAgo: "5h", seller: "Pearl Realty", sellerSince: "2019", featured: false, condition: "Furnished", swatch: "neutral", tags: ["Sea View", "Gym & Pool", "Parking"], thumbs: 8, photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=75&auto=format&fit=crop", desc: "Fully furnished two-bedroom apartment with panoramic marina views. Building amenities include 24/7 security, gym, two pools, kids play area." },
  { id: "L-2404", title: "Mid-Century Walnut Dining Table — Seats 8", price: 3800, currency: "QAR", category: "furniture", subcategory: "Dining", location: "Al Sadd, Doha", postedAgo: "1d", seller: "Hessa K.", sellerSince: "2022", featured: false, condition: "Used", swatch: "earth", tags: ["Solid Wood", "Negotiable"], thumbs: 5, photo: "https://images.unsplash.com/photo-1617104551722-3b2d51366400?w=800&q=75&auto=format&fit=crop", desc: "Beautiful solid walnut dining table, gently used. Moving sale. Pickup only — table is heavy." },
  { id: "L-2405", title: "MacBook Pro 14\" M3 Pro — 18GB / 1TB", price: 8900, currency: "QAR", category: "electronics", subcategory: "Laptops", location: "Education City", postedAgo: "4h", seller: "Omar S.", sellerSince: "2020", featured: false, condition: "Like New", swatch: "cool", tags: ["AppleCare+", "Box & Charger"], thumbs: 3, photo: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=75&auto=format&fit=crop", desc: "Bought 4 months ago, used lightly for design work. AppleCare+ valid until 2027. All original accessories." },
  { id: "L-2406", title: "Bilingual Marketing Manager — Doha HQ", price: 28000, currency: "QAR/mo", category: "jobs", subcategory: "Full-time", location: "Doha", postedAgo: "6h", seller: "Qatar Logistics Co.", sellerSince: "2018", featured: true, condition: "Permanent", swatch: "warm", tags: ["Arabic + English", "5+ yrs exp"], thumbs: 1, photo: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=75&auto=format&fit=crop", desc: "Lead the marketing function for a fast-growing logistics company. Reporting to CMO. Excellent benefits + housing + transport allowance." },
  { id: "L-2407", title: "Sony A7 IV Mirrorless + 24-70mm GM Lens Kit", price: 11500, currency: "QAR", category: "electronics", subcategory: "Cameras", location: "Mushaireb, Doha", postedAgo: "2d", seller: "Yusuf R.", sellerSince: "2022", featured: false, condition: "Used", swatch: "neutral", tags: ["< 5k Shutter", "Box"], thumbs: 6, photo: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&q=75&auto=format&fit=crop", desc: "Professional mirrorless kit in mint condition. Always kept in dry box. Shutter count under 5,000. Box, straps, two batteries." },
  { id: "L-2408", title: "Maine Coon Kitten — Vaccinated, Microchipped", price: 4500, currency: "QAR", category: "pets", subcategory: "Cats", location: "Al Khor", postedAgo: "8h", seller: "Mariam H.", sellerSince: "2023", featured: false, condition: "12 weeks", swatch: "warm", tags: ["TICA Pedigree", "Vet Records"], thumbs: 4, photo: "https://images.unsplash.com/photo-1543852786-1cf6624b9987?w=800&q=75&auto=format&fit=crop", desc: "Pedigreed Maine Coon kitten, raised in our home with children. Full vet records, microchipped, first vaccines done." },
  { id: "L-2409", title: "Professional Deep Cleaning — Villas & Apartments", price: 350, currency: "QAR/visit", category: "services", subcategory: "Cleaning", location: "All Doha", postedAgo: "3h", seller: "SparkleClean", sellerSince: "2020", featured: false, condition: "Service", swatch: "cool", tags: ["Insured", "Same Day"], thumbs: 1, photo: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=75&auto=format&fit=crop", desc: "Eco-friendly products, trained team, fully insured. Same-day booking available. Discounts for weekly contracts." },
  { id: "L-2410", title: "Designer Tote Bag — Authenticated, Receipt Included", price: 78000, currency: "QAR", category: "fashion", subcategory: "Bags", location: "The Pearl", postedAgo: "1d", seller: "Reem A.", sellerSince: "2021", featured: true, condition: "Pristine", swatch: "earth", tags: ["Authenticated", "Dust Bag"], thumbs: 7, photo: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=75&auto=format&fit=crop", desc: "Pristine designer tote in soft leather with palladium hardware. Full set: box, dust bag, receipt, raincoat. Authentication papers included." },
  { id: "L-2411", title: "Smart Indoor Cycling Bike with Shoes & 1yr Membership", price: 6200, currency: "QAR", category: "sports", subcategory: "Fitness", location: "Lusail", postedAgo: "12h", seller: "Tariq B.", sellerSince: "2022", featured: false, condition: "Used", swatch: "neutral", tags: ["Membership Transfer"], thumbs: 3, photo: "https://images.unsplash.com/photo-1591741535018-d042766c62eb?w=800&q=75&auto=format&fit=crop", desc: "Excellent condition smart bike. Includes size 44 shoes and one year of membership transferable to buyer. Selling because we relocated." },
  { id: "L-2412", title: "Cozy Studio for Rent — Mansoura, Bills Included", price: 3200, currency: "QAR/mo", category: "property", subcategory: "Rooms", location: "Mansoura, Doha", postedAgo: "1d", seller: "Ahmed T.", sellerSince: "2020", featured: false, condition: "Furnished", swatch: "earth", tags: ["Wi-Fi", "Bills Inc."], thumbs: 4, photo: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=75&auto=format&fit=crop", desc: "Bright furnished studio in a quiet building. All bills (DEWA, internet) included. Walking distance to metro." },
];

// Sample conversations for messages page
window.BAZZAR_THREADS = [
  { id: "T1", listingId: "L-2401", partner: "Khalid M.", lastMsg: "Yes, the price is negotiable for serious buyers. When can you come see it?", time: "10:42", unread: 2, online: true,
    messages: [
      { from: "me",   text: "Hi, is this still available?", time: "10:30" },
      { from: "them", text: "Yes, it is. Are you a serious buyer?", time: "10:34" },
      { from: "me",   text: "Yes. Is the price negotiable? Could we meet this weekend?", time: "10:39" },
      { from: "them", text: "Yes, the price is negotiable for serious buyers. When can you come see it?", time: "10:42" },
    ]},
  { id: "T2", listingId: "L-2402", partner: "Layla A.",    lastMsg: "Sealed box, with regional warranty. I can meet at City Center.", time: "Yesterday", unread: 0, online: false },
  { id: "T3", listingId: "L-2403", partner: "Pearl Realty",lastMsg: "Viewing slot confirmed for Sat 4pm. Please bring ID.",            time: "Yesterday", unread: 0, online: true  },
  { id: "T4", listingId: "L-2410", partner: "Reem A.",     lastMsg: "I have all original paperwork. Where would you like to meet?",     time: "Wed",       unread: 1, online: false },
  { id: "T5", listingId: "L-2407", partner: "Yusuf R.",    lastMsg: "Sorry, just sold this one. Will list a backup body next week.",   time: "Tue",       unread: 0, online: false },
];

window.BAZZAR_FAQ = [
  { q: "How do I post my first ad?", a: "Click 'Post an ad' in the top right, pick a category, fill in the details, add up to 20 photos, and publish. Most ads go live in under a minute." },
  { q: "Is Bazzar free to use?", a: "Yes. Posting and browsing are free. We charge only for optional visibility upgrades like 'Featured' or 'Bump up' which keep your ad near the top of search results." },
  { q: "How do I keep myself safe when meeting a buyer or seller?", a: "Meet in public, well-lit places (mall food courts and petrol stations are great). Bring a friend for large items. Inspect goods before exchanging cash. Never wire money to a stranger." },
  { q: "Can I delete or edit an ad after publishing?", a: "Yes. Go to My Ads → pick the listing → Edit or Delete. Edits go live instantly. Sold items can be marked 'Sold' to keep your reputation visible without deleting." },
  { q: "How does the rating system work?", a: "After every completed exchange, both parties can leave a star rating and short review. Your rating shows next to your profile name on every listing." },
  { q: "What can't I sell on Bazzar?", a: "Anything illegal in Qatar, counterfeit goods, alcohol, weapons, prescription medication, live wildlife, and recalled products. Full list in our Posting Policy." },
  { q: "How do I report a suspicious listing?", a: "Every listing has a 'Report' link below the description. Reports are reviewed within 24 hours by our trust & safety team." },
  { q: "What is 'Featured' and how much does it cost?", a: "Featured ads appear in the carousel on the homepage and at the top of category pages for 7 days. Pricing varies by category, starting from QAR 25." },
];
