<?php

declare(strict_types=1);

namespace App\Notifications;

use App\Enums\Language;
use App\Models\User;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Notifies the user that their personal-data export is ready, with a signed,
 * time-limited download URL.
 *
 * The URL is generated by ExportUserDataJob using
 * `URL::temporarySignedRoute('account.data-export.download', …)` — the route
 * itself verifies the signature, expiry, and ownership before streaming the
 * file. We just deliver the link; the route does the gatekeeping.
 */
class DataExportReadyNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        public readonly string $downloadUrl,
        public readonly int $expiresInHours,
    ) {}

    /**
     * @return array<int, string>
     */
    public function via(mixed $notifiable): array
    {
        return $notifiable instanceof User
            ? ['mail', 'database']
            : ['mail'];
    }

    /**
     * Lightweight DB payload — the actual signed URL isn't stored, only a
     * pointer that opens the account/data-export page where the user can
     * re-request the link if it expired. We deliberately keep the signed
     * URL out of the persisted notification because the URL grants
     * download access; surfacing it in the bell list would re-expose it
     * indefinitely.
     *
     * @return array<string, mixed>
     */
    public function toArray(mixed $notifiable): array
    {
        $locale = $this->resolveLocale($notifiable);

        return [
            'category' => 'account.data_export_ready',
            'title' => __('messages.notifications.data_export_ready.title', [], $locale),
            'body' => __('messages.notifications.data_export_ready.body', [], $locale),
            'cta_url' => rtrim((string) config('qbazaar.web_url', config('app.url')), '/') . '/account/data-export',
            'icon' => 'download',
            'expires_in_hours' => $this->expiresInHours,
        ];
    }

    public function toMail(mixed $notifiable): MailMessage
    {
        $locale = $this->resolveLocale($notifiable);

        return (new MailMessage)
            ->subject(__('messages.data_export.mail.subject', [], $locale))
            ->greeting(__('messages.data_export.mail.greeting', [], $locale))
            ->line(__('messages.data_export.mail.line_intro', [], $locale))
            ->action(__('messages.data_export.mail.action', [], $locale), $this->downloadUrl)
            ->line(__('messages.data_export.mail.line_expires', ['hours' => $this->expiresInHours], $locale))
            ->line(__('messages.data_export.mail.line_ignore', [], $locale));
    }

    private function resolveLocale(mixed $notifiable): string
    {
        if ($notifiable instanceof User) {
            return $notifiable->language instanceof Language
                ? $notifiable->language->value
                : (string) config('qbazaar.default_language', 'ar');
        }

        return (string) config('qbazaar.default_language', 'ar');
    }
}
